version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql_br
    environment:
      MYSQL_ROOT_PASSWORD: marcos1985
      MYSQL_DATABASE: anotacoes_br
      TZ: America/Sao_Paulo
      LANG: pt_BR.UTF-8
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appWebContas
    ports:
      - "9090:8080"
    depends_on:
      - mysql
